"""
Marking AI-generated content (EU AI Act Art. 50(2)).

From 2 December 2026, providers of systems generating synthetic image, audio,
video or text must mark the output in a machine-readable form so it can be
detected as artificially generated.

The interoperable marker for this is the IPTC digital source type
`trainedAlgorithmicMedia`, carried in an XMP packet — the same marker the major
image generators write. It is embedded here directly rather than through an
imaging library: MATE generates PNG, PNG metadata is an `iTXt` chunk, and writing
one is less code than the dependency would be.

This is a marker, not a signature. It states provenance to anything that reads
the file; it does not prove it, and it can be stripped by re-encoding. C2PA
adds cryptographic signing on top and is the natural next step, but it needs a
signing identity that MATE has no way to provision for its users.
"""

import logging
import struct
import zlib
from typing import Optional

logger = logging.getLogger(__name__)

PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"

# IPTC NewsCodes term for media created wholly by a generative model.
DIGITAL_SOURCE_TYPE = "http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia"

_XMP_KEYWORD = b"XML:com.adobe.xmp"

_XMP_TEMPLATE = """<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:Iptc4xmpExt="http://iptc.org/std/Iptc4xmpExt/2008-02-29/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:xmp="http://ns.adobe.com/xap/1.0/">
   <Iptc4xmpExt:DigitalSourceType>{source_type}</Iptc4xmpExt:DigitalSourceType>
   <xmp:CreatorTool>{creator_tool}</xmp:CreatorTool>
   <dc:description>{description}</dc:description>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>"""


def _escape(value: str) -> str:
    return (value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


def build_xmp(creator_tool: str = "MATE", description: str = "AI-generated image") -> str:
    """The XMP packet declaring this content as generated by a trained model."""
    return _XMP_TEMPLATE.format(
        source_type=DIGITAL_SOURCE_TYPE,
        creator_tool=_escape(creator_tool),
        description=_escape(description),
    )


def _itxt_chunk(payload: bytes) -> bytes:
    """
    An uncompressed iTXt chunk carrying an XMP packet.

    Layout after the keyword: null, compression flag, compression method,
    language tag, null, translated keyword, null, then the text.
    """
    data = _XMP_KEYWORD + b"\x00" + b"\x00" + b"\x00" + b"\x00" + b"\x00" + payload
    chunk_type = b"iTXt"
    return (
        struct.pack(">I", len(data))
        + chunk_type
        + data
        + struct.pack(">I", zlib.crc32(chunk_type + data) & 0xFFFFFFFF)
    )


def mark_png_as_ai_generated(png_bytes: bytes,
                             creator_tool: str = "MATE",
                             description: str = "AI-generated image") -> bytes:
    """
    Return the PNG with an XMP packet marking it as AI-generated.

    Returns the input unchanged if it is not a PNG, or if anything goes wrong:
    an image that reaches the user unmarked is a compliance gap, but an image
    corrupted while marking it is a broken product. The caller logs the gap.
    """
    if not png_bytes or not png_bytes.startswith(PNG_SIGNATURE):
        logger.warning(
            "Not marking generated content: expected a PNG, got %s bytes starting "
            "%r. The file is passed through unmarked.",
            len(png_bytes or b""), (png_bytes or b"")[:8])
        return png_bytes

    try:
        # IHDR must stay first, so the marker goes immediately after it.
        ihdr_length = struct.unpack(">I", png_bytes[8:12])[0]
        ihdr_end = 8 + 4 + 4 + ihdr_length + 4
        if png_bytes[12:16] != b"IHDR":
            logger.warning("Not marking generated content: first chunk is not IHDR.")
            return png_bytes

        chunk = _itxt_chunk(build_xmp(creator_tool, description).encode("utf-8"))
        return png_bytes[:ihdr_end] + chunk + png_bytes[ihdr_end:]
    except Exception as exc:
        logger.error("Failed to mark generated content, passing it through: %s", exc)
        return png_bytes


def read_xmp(png_bytes: bytes) -> Optional[str]:
    """The XMP packet embedded in a PNG, or None. Used to verify a round trip."""
    if not png_bytes or not png_bytes.startswith(PNG_SIGNATURE):
        return None
    offset = 8
    while offset + 8 <= len(png_bytes):
        length = struct.unpack(">I", png_bytes[offset:offset + 4])[0]
        chunk_type = png_bytes[offset + 4:offset + 8]
        data = png_bytes[offset + 8:offset + 8 + length]
        if chunk_type == b"iTXt" and data.startswith(_XMP_KEYWORD + b"\x00"):
            return data[len(_XMP_KEYWORD) + 5:].decode("utf-8", errors="replace")
        if chunk_type == b"IEND":
            break
        offset += 12 + length
    return None


def is_marked_as_ai_generated(png_bytes: bytes) -> bool:
    """Whether the file carries the trained-algorithmic-media marker."""
    xmp = read_xmp(png_bytes)
    return bool(xmp and DIGITAL_SOURCE_TYPE in xmp)
