#!/usr/bin/env python3
"""Generate and check MATE's documentation.

The docs tree has two kinds of pages:

* ``docs/reference/*.md`` is generated from the code by this script and is
  never edited by hand. It cannot drift: CI regenerates it and fails when the
  committed copy differs.
* ``docs/user/*.md`` and ``docs/dev/*.md`` are guides written by people (or by
  an agent and reviewed by people). Each one declares, in its frontmatter, the
  code it describes (``covers:``). When that code changes and the guide does
  not, the guide is reported as possibly stale.

Usage::

    python scripts/gen_docs.py                 # regenerate docs/reference/
    python scripts/gen_docs.py --check         # CI: reference up to date + guides well-formed
    python scripts/gen_docs.py drift --base origin/main [--strict]
    python scripts/gen_docs.py coverage        # which source files no guide covers

Everything here is static analysis (``ast``) over the working tree. Nothing is
imported from the application, so the script needs no dependencies, no database
and no running server, and its output is deterministic: no timestamps and no
line numbers, both of which would make the reference "change" on every commit.
"""

from __future__ import annotations

import argparse
import ast
import fnmatch
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Set, Tuple

ROOT = Path(__file__).resolve().parent.parent
DOCS_DIR = ROOT / "docs"
REFERENCE_DIR = DOCS_DIR / "reference"
GUIDE_DIRS = {"user": DOCS_DIR / "user", "dev": DOCS_DIR / "dev"}

GENERATED_BANNER = (
    "<!-- AUTO-GENERATED by scripts/gen_docs.py. Do not edit: "
    "change the code, then run `python scripts/gen_docs.py`. -->"
)

# Directories that never hold application code worth documenting.
SKIP_DIRS = {
    ".git", ".venv", "venv", "node_modules", "__pycache__", "build", "dist",
    ".codegraph", ".claude",
}
# Tests read env vars and declare routes of their own; they are not the product.
SKIP_PREFIXES = ("shared/test/", "scripts/gen_docs.py")

# These are managed by the application, rather than configured by operators.
ENV_EXAMPLE_ALLOWLIST = {
    "TIKTOKEN_CACHE_DIR": "build_standalone_agent.py sets the tokenizer cache directory",
}

# Source areas a guide is expected to cover, for the coverage report.
COVERAGE_GLOBS = (
    "auth_server.py", "adk_main.py", "langgraph_main.py", "standalone_server.py",
    "server/**", "shared/callbacks/**", "shared/utils/**",
    "templates/dashboard/**", "static/js/**",
)

HTTP_METHODS = {"get", "post", "put", "delete", "patch", "websocket", "api_route"}
SQL_DIALECTS = ("sqlite", "postgresql", "mysql")


# --------------------------------------------------------------------------- #
# Files                                                                        #
# --------------------------------------------------------------------------- #

def rel(path: Path) -> str:
    """Repo-relative path with forward slashes."""
    return path.relative_to(ROOT).as_posix()


def tracked_files() -> List[str]:
    """Every file in the repo, preferring git's view and falling back to a walk.

    Untracked files that are not ignored are included, so a new module shows up
    before it is staged. Keep scratch scripts ignored or outside the repo, or
    they will appear in the reference locally and not in CI.
    """
    try:
        out = subprocess.run(
            ["git", "ls-files", "--cached", "--others", "--exclude-standard"],
            cwd=ROOT, capture_output=True, text=True, check=True,
        ).stdout
        files = [line for line in out.splitlines() if line and (ROOT / line).is_file()]
        if files:
            return sorted(files)
    except (OSError, subprocess.CalledProcessError):
        pass
    found: List[str] = []
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for name in filenames:
            found.append(rel(Path(dirpath) / name))
    return sorted(found)


def python_sources(files: Sequence[str]) -> List[str]:
    return [
        f for f in files
        if f.endswith(".py")
        and not f.startswith(SKIP_PREFIXES)
        and not (set(f.split("/")) & SKIP_DIRS)
    ]


def parse(path: str) -> Optional[ast.Module]:
    try:
        return ast.parse((ROOT / path).read_text(encoding="utf-8"), filename=path)
    except (SyntaxError, UnicodeDecodeError, OSError):
        return None


def glob_to_regex(pattern: str) -> "re.Pattern[str]":
    """Translate a path glob to a regex. ``**`` spans directories, ``*`` does not."""
    out = []
    i = 0
    while i < len(pattern):
        if pattern.startswith("**/", i):
            out.append("(?:.*/)?")
            i += 3
        elif pattern.startswith("**", i):
            out.append(".*")
            i += 2
        elif pattern[i] == "*":
            out.append("[^/]*")
            i += 1
        elif pattern[i] == "?":
            out.append("[^/]")
            i += 1
        else:
            out.append(re.escape(pattern[i]))
            i += 1
    return re.compile("^" + "".join(out) + "$")


# --------------------------------------------------------------------------- #
# Markdown helpers                                                             #
# --------------------------------------------------------------------------- #

def cell(text: Any) -> str:
    """Make a value safe for a Markdown table cell."""
    s = "" if text is None else str(text)
    s = re.sub(r"\s+", " ", s).strip()
    return s.replace("|", "\\|") or "—"


def code(text: Any) -> str:
    s = "" if text is None else str(text)
    return f"`{s}`" if s else "—"


def table(headers: Sequence[str], rows: Iterable[Sequence[str]]) -> str:
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    lines.extend("| " + " | ".join(row) + " |" for row in rows)
    return "\n".join(lines)


def page(title: str, summary: str, order: int, body: str) -> str:
    front = "\n".join([
        "---",
        f"title: {title}",
        f"summary: {summary}",
        "audience: dev",
        f"order: {order}",
        "generated: true",
        "---",
    ])
    return f"{front}\n\n{GENERATED_BANNER}\n\n# {title}\n\n{body.rstrip()}\n"


def first_line(doc: Optional[str]) -> str:
    """The first sentence of a docstring's first paragraph, without the full stop."""
    if not doc:
        return ""
    paragraph = " ".join(doc.strip().split("\n\n", 1)[0].split())
    sentence = re.split(r"(?<=[.!?])\s", paragraph, maxsplit=1)[0]
    if len(sentence) > 180:
        sentence = sentence[:177].rstrip() + "..."
    return sentence.rstrip(".")


def dotted(node: ast.AST) -> str:
    """``a.b.c`` for a Name/Attribute chain, else an empty string."""
    parts: List[str] = []
    while isinstance(node, ast.Attribute):
        parts.append(node.attr)
        node = node.value
    if isinstance(node, ast.Name):
        parts.append(node.id)
        return ".".join(reversed(parts))
    return ""


def const_str(node: Optional[ast.AST]) -> Optional[str]:
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    return None


# --------------------------------------------------------------------------- #
# Reference: configuration (environment variables)                             #
# --------------------------------------------------------------------------- #

ENV_NAME = re.compile(r"^[A-Z][A-Z0-9_]*$")
ENV_EXAMPLE_VAR = re.compile(r"^\s*#?\s*([A-Z][A-Z0-9_]*)=(.*)$")
ENV_EXAMPLE_CONTINUATION = re.compile(r"^#\s+#\s?(.*)$")


ENV_READERS = ("os.getenv", "os.environ.get", "environ.get", "getenv")
# Read by the code, but the operating system's business rather than MATE's.
ENV_IGNORED = {"PATH"}


def env_wrappers(tree: ast.Module) -> Dict[str, Optional[str]]:
    """Module-local helpers that forward their first argument to ``os.getenv``.

    ``def _cfg(key, default=""): return os.getenv(key, default)`` makes every
    ``_cfg("NAME")`` an env read. Maps the helper's name to its own default.
    """
    wrappers: Dict[str, Optional[str]] = {}
    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) or not node.args.args:
            continue
        first = node.args.args[0].arg
        forwards = any(
            isinstance(call, ast.Call) and dotted(call.func) in ENV_READERS and call.args
            and isinstance(call.args[0], ast.Name) and call.args[0].id == first
            for call in ast.walk(node)
        )
        if not forwards:
            continue
        default: Optional[str] = None
        if len(node.args.args) > 1 and node.args.defaults:
            last = node.args.defaults[-1]
            if isinstance(last, ast.Constant) and last.value is not None:
                default = str(last.value)
        wrappers[node.name] = default
    return wrappers


def collect_env_reads(sources: Sequence[str]) -> Dict[str, Dict[str, Set[str]]]:
    """Map each env var read in code to the files reading it and the defaults used."""
    found: Dict[str, Dict[str, Set[str]]] = {}

    def record(name: str, path: str, default: Optional[str]) -> None:
        if not ENV_NAME.match(name) or name in ENV_IGNORED:
            return
        entry = found.setdefault(name, {"files": set(), "defaults": set()})
        entry["files"].add(path)
        if default is not None:
            entry["defaults"].add(default)

    for path in sources:
        tree = parse(path)
        if tree is None:
            continue
        wrappers = env_wrappers(tree)
        for node in ast.walk(tree):
            if isinstance(node, ast.Call):
                target = dotted(node.func)
                if (target in ENV_READERS or target in wrappers) and node.args:
                    name = const_str(node.args[0])
                    if name is None:
                        continue
                    default_node = node.args[1] if len(node.args) > 1 else None
                    for kw in node.keywords:
                        if kw.arg == "default":
                            default_node = kw.value
                    if default_node is None:
                        default = wrappers.get(target)
                    elif isinstance(default_node, ast.Constant):
                        default = None if default_node.value is None else str(default_node.value)
                    else:
                        default = "(computed)"
                    record(name, path, default)
            elif isinstance(node, ast.Subscript) and isinstance(node.ctx, ast.Load):
                if dotted(node.value) in ("os.environ", "environ"):
                    name = const_str(node.slice)
                    if name is not None:
                        record(name, path, None)
    return found


def parse_env_example() -> Dict[str, Dict[str, str]]:
    """Read ``.env.example``: the example value and the comment explaining each variable."""
    path = ROOT / ".env.example"
    if not path.is_file():
        return {}
    lines = path.read_text(encoding="utf-8").splitlines()
    result: Dict[str, Dict[str, str]] = {}
    pending_comment: List[str] = []
    pending_start = -1
    i = 0
    while i < len(lines):
        line = lines[i]
        match = ENV_EXAMPLE_VAR.match(line)
        if match:
            name, rest = match.group(1), match.group(2)
            value, _, inline = rest.partition(" #")
            description = [inline.strip()] if inline.strip() else []
            while i + 1 < len(lines):
                cont = ENV_EXAMPLE_CONTINUATION.match(lines[i + 1])
                if not cont:
                    break
                description.append(cont.group(1).strip())
                i += 1
            # A comment block directly above a variable describes it, unless it is
            # the banner at the top of the file.
            if not description and pending_comment and pending_start > 0:
                description = pending_comment
            result.setdefault(name, {
                "example": value.strip(),
                "description": " ".join(d for d in description if d),
            })
            pending_comment = []
        elif line.strip().startswith("#"):
            text = line.strip().lstrip("#").strip()
            if text:
                if not pending_comment:
                    pending_start = i
                pending_comment.append(text)
        else:
            pending_comment = []
        i += 1
    return result


def configuration_gaps(
    reads: Dict[str, Dict[str, Set[str]]], example: Dict[str, Dict[str, str]],
) -> Tuple[List[str], List[str]]:
    """Conflicting defaults and reads without an entry in the env template."""
    conflicts = sorted(name for name, entry in reads.items() if len(entry["defaults"]) > 1)
    undocumented = sorted(name for name in reads if name not in example)
    return conflicts, undocumented


def render_configuration(sources: Sequence[str]) -> str:
    reads = collect_env_reads(sources)
    example = parse_env_example()
    conflicts, undocumented = configuration_gaps(reads, example)
    unread = sorted(n for n in example if n not in reads)

    rows = []
    for name in sorted(reads):
        entry = reads[name]
        defaults = sorted(entry["defaults"])
        default_text = " / ".join(code(d) for d in defaults) if defaults else "—"
        if name in conflicts:
            default_text += " ⚠"
        files = sorted(entry["files"])
        shown = ", ".join(code(f) for f in files[:3])
        if len(files) > 3:
            shown += f" +{len(files) - 3} more"
        rows.append([
            code(name), default_text,
            cell(example.get(name, {}).get("description", "")), shown,
        ])

    body = [
        f"Every environment variable the code reads: **{len(reads)}** in total. "
        "Descriptions come from the comments in `.env.example`; defaults come from the "
        "code. A ⚠ marks a variable read with different defaults in different places.",
        "",
        table(["Variable", "Default", "Description", "Read in"], rows),
    ]
    if undocumented:
        body += [
            "", "## Read by the code but missing from `.env.example`", "",
            f"{len(undocumented)} variables have no entry (and so no description) in "
            "`.env.example`:", "",
            ", ".join(code(n) for n in undocumented),
        ]
    if unread:
        body += [
            "", "## In `.env.example` but not read by MATE's own code", "",
            "Usually consumed by a library (LiteLLM provider keys, OpenTelemetry, "
            "LangSmith) rather than by MATE directly; otherwise a leftover:", "",
            ", ".join(code(n) for n in unread),
        ]
    return page(
        "Configuration reference",
        "Every environment variable MATE reads, with defaults and where it is used.",
        10, "\n".join(body),
    )


# --------------------------------------------------------------------------- #
# Reference: HTTP API                                                          #
# --------------------------------------------------------------------------- #

def collect_tag_descriptions() -> Dict[str, str]:
    tree = parse("auth_server.py")
    tags: Dict[str, str] = {}
    if tree is None:
        return tags
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign) and any(
            isinstance(t, ast.Name) and t.id == "tags_metadata" for t in node.targets
        ) and isinstance(node.value, ast.List):
            for item in node.value.elts:
                if not isinstance(item, ast.Dict):
                    continue
                pairs = {const_str(k): const_str(v) for k, v in zip(item.keys, item.values)}
                if pairs.get("name"):
                    tags[pairs["name"]] = pairs.get("description") or ""
    return tags


def path_literal(node: ast.AST) -> Optional[str]:
    """A route path, including f-strings (rendered with their ``{expr}`` holes)."""
    literal = const_str(node)
    if literal is not None:
        return literal
    if isinstance(node, ast.JoinedStr):
        out = []
        for part in node.values:
            if isinstance(part, ast.Constant):
                out.append(str(part.value))
            elif isinstance(part, ast.FormattedValue):
                out.append("{" + ast.unparse(part.value) + "}")
        return "".join(out)
    return None


def collect_routes(sources: Sequence[str]) -> List[Dict[str, str]]:
    routes: List[Dict[str, str]] = []
    for path in sources:
        tree = parse(path)
        if tree is None:
            continue

        routers: Dict[str, Dict[str, Any]] = {}
        for node in ast.walk(tree):
            if isinstance(node, ast.Assign) and isinstance(node.value, ast.Call) \
                    and dotted(node.value.func).endswith("APIRouter"):
                prefix, tags = "", []
                for kw in node.value.keywords:
                    if kw.arg == "prefix":
                        prefix = const_str(kw.value) or ""
                    elif kw.arg == "tags" and isinstance(kw.value, ast.List):
                        tags = [const_str(e) for e in kw.value.elts if const_str(e)]
                for target in node.targets:
                    if isinstance(target, ast.Name):
                        routers[target.id] = {"prefix": prefix, "tags": tags}

        for node in ast.walk(tree):
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            for dec in node.decorator_list:
                if not (isinstance(dec, ast.Call) and isinstance(dec.func, ast.Attribute)):
                    continue
                method = dec.func.attr
                if method not in HTTP_METHODS or not dec.args:
                    continue
                route_path = path_literal(dec.args[0])
                if route_path is None:
                    continue
                owner = dotted(dec.func.value)
                router = routers.get(owner, {"prefix": "", "tags": []})
                tags = list(router["tags"])
                methods = [method.upper()]
                for kw in dec.keywords:
                    if kw.arg == "tags" and isinstance(kw.value, ast.List):
                        tags = [const_str(e) for e in kw.value.elts if const_str(e)] or tags
                    elif kw.arg == "methods" and isinstance(kw.value, ast.List):
                        methods = [const_str(e) for e in kw.value.elts if const_str(e)]
                if method == "websocket":
                    methods = ["WS"]
                elif method == "api_route" and methods == ["API_ROUTE"]:
                    methods = ["ANY"]
                routes.append({
                    "method": ", ".join(methods),
                    "path": router["prefix"] + route_path,
                    "tag": tags[0] if tags else "Untagged",
                    "summary": first_line(ast.get_docstring(node)),
                    "source": f"{path} · {node.name}",
                })
    return routes


# Which process serves a route, decided by the file that declares it. Order matters:
# first match wins, and the last entry is the catch-all.
SERVERS = (
    ("Agent server: ADK runtime", "Internal, port 8001. Reached through the auth "
     "server's proxy, not exposed directly.", ("adk_main.py",)),
    ("Agent server: LangGraph runtime", "Used instead of the ADK runtime when "
     "`AGENT_FRAMEWORK=langgraph`; emulates the same HTTP/SSE contract.",
     ("langgraph_main.py", "shared/utils/langgraph/**")),
    ("Standalone server", "The single-agent binary built by "
     "`build_standalone_agent.py`.", ("standalone_server.py",)),
    ("Auth server and dashboard", "Port 8000. Everything a browser or an external "
     "client talks to.", ("**",)),
)


def server_for(source_file: str) -> str:
    for name, _, patterns in SERVERS:
        if any(glob_to_regex(p).match(source_file) for p in patterns):
            return name
    return SERVERS[-1][0]


def render_api(sources: Sequence[str]) -> str:
    routes = collect_routes(sources)
    descriptions = collect_tag_descriptions()
    grouped: Dict[str, Dict[str, List[Dict[str, str]]]] = {}
    for route in routes:
        server = server_for(route["source"].split(" · ")[0])
        grouped.setdefault(server, {}).setdefault(route["tag"], []).append(route)

    undocumented = sum(1 for r in routes if not r["summary"])
    body = [
        f"Every HTTP route declared in the code: **{len(routes)}** routes. "
        f"{undocumented} have no docstring and so no summary here.",
        "",
        "This page lists what exists and where it is implemented. For request and "
        "response schemas, and to try a call, use the live Swagger UI under "
        "**Documentation → API** in the dashboard.",
        "",
        "Requests to `/dashboard/api/*` require an admin, apart from the short allowlist "
        "in `server/dashboard_authz.py`.",
    ]
    # Catch-all (the public surface) first, then the internal servers.
    for name, blurb, _ in (SERVERS[-1],) + SERVERS[:-1]:
        tags = grouped.get(name)
        if not tags:
            continue
        count = sum(len(v) for v in tags.values())
        body += ["", f"## {name}", "", f"{blurb} {count} routes."]
        for tag in sorted(tags, key=lambda t: (t == "Untagged", t)):
            body += ["", f"### {'Other' if tag == 'Untagged' else tag}", ""]
            if descriptions.get(tag):
                body += [descriptions[tag].rstrip(".") + ".", ""]
            rows = [
                [code(r["method"]), code(r["path"]), cell(r["summary"]), cell(r["source"])]
                for r in sorted(tags[tag], key=lambda r: (r["path"], r["method"]))
            ]
            body.append(table(["Method", "Path", "Summary", "Implemented in"], rows))
    return page(
        "HTTP API reference",
        "Every HTTP route, grouped by server and area, with a summary and where it lives.",
        20, "\n".join(body),
    )


# --------------------------------------------------------------------------- #
# Reference: tools                                                             #
# --------------------------------------------------------------------------- #

TOOL_FACTORY = "shared/utils/tools/tool_factory.py"


def render_tools() -> str:
    tree = parse(TOOL_FACTORY)
    creators: Dict[str, str] = {}
    methods: Dict[str, ast.FunctionDef] = {}
    special: Set[str] = set()
    if tree is not None:
        for node in ast.walk(tree):
            if isinstance(node, ast.ClassDef) and node.name == "ToolFactory":
                for item in node.body:
                    if isinstance(item, ast.FunctionDef):
                        methods[item.name] = item
            if isinstance(node, ast.Assign) and isinstance(node.value, ast.Dict) and any(
                dotted(t) == "self._tool_creators" for t in node.targets
            ):
                for key, value in zip(node.value.keys, node.value.values):
                    name = const_str(key)
                    if name and isinstance(value, ast.Attribute):
                        creators[name] = value.attr
            # tool_config keys handled inline rather than through the registry
            if isinstance(node, ast.Compare) and dotted(node.left) == "tool_type" \
                    and len(node.ops) == 1 and isinstance(node.ops[0], ast.Eq):
                literal = const_str(node.comparators[0])
                if literal:
                    special.add(literal)

    rows = []
    for key in sorted(creators):
        method = methods.get(creators[key])
        description, module = "", ""
        if method is not None:
            description = first_line(ast.get_docstring(method))
            for sub in ast.walk(method):
                if isinstance(sub, ast.ImportFrom) and sub.module:
                    base = "shared/utils/tools/" if sub.level == 1 else ""
                    module = base + sub.module.replace(".", "/") + ".py"
                    break
        rows.append([code(key), cell(description), code(module)])

    inline_only = sorted(special - set(creators))
    body = [
        f"The tool types an agent can enable through its `tool_config` JSON: "
        f"**{len(creators)}** registered in `ToolFactory._tool_creators`.",
        "",
        "A key enables its tools when present with a non-null value, for example "
        '`{"memory_blocks": true, "file_search": true}`.',
        "",
        table(["`tool_config` key", "What it adds", "Implemented in"], rows),
    ]
    if inline_only:
        body += [
            "", "## Keys handled outside the registry", "",
            "Handled by a dedicated branch in `ToolFactory.create_tools` rather than a "
            "registered creator:", "",
            ", ".join(code(k) for k in inline_only),
        ]
    return page(
        "Tool reference",
        "Every tool type an agent can enable through tool_config, and where it is implemented.",
        30, "\n".join(body),
    )


# --------------------------------------------------------------------------- #
# Reference: database                                                          #
# --------------------------------------------------------------------------- #

MODELS = "shared/utils/models.py"
MIGRATION_FILE = re.compile(r"^V(\d+)__(.+)\.sql$")


def column_comment(lines: Sequence[str], node: ast.Assign) -> str:
    """The comment explaining a column: trailing on its line, else the block above it."""
    for lineno in range(node.lineno, (node.end_lineno or node.lineno) + 1):
        _, sep, trailing = lines[lineno - 1].partition("  # ")
        if sep:
            return trailing.strip()
    block: List[str] = []
    lineno = node.lineno - 2
    while lineno >= 0 and lines[lineno].strip().startswith("#"):
        block.insert(0, lines[lineno].strip().lstrip("#").strip())
        lineno -= 1
    return " ".join(block)


def migration_versions() -> Dict[int, Dict[str, str]]:
    """{version: {dialect: name}} for every migration file in the dialect folders."""
    versions: Dict[int, Dict[str, str]] = {}
    for dialect in SQL_DIALECTS:
        folder = ROOT / "shared" / "sql" / "migrations" / dialect
        if not folder.is_dir():
            continue
        for entry in folder.iterdir():
            match = MIGRATION_FILE.match(entry.name)
            if match:
                versions.setdefault(int(match.group(1)), {})[dialect] = match.group(2)
    return versions


def migration_gaps() -> List[str]:
    """Each migration version missing from a dialect, e.g. ``V036 has no mysql file``.

    An installation on that database type would silently never get the change.
    """
    return [
        f"V{version:03d} has no {dialect} file"
        for version, present in sorted(migration_versions().items())
        for dialect in SQL_DIALECTS if dialect not in present
    ]


def render_database() -> str:
    tree = parse(MODELS)
    lines = (ROOT / MODELS).read_text(encoding="utf-8").splitlines() if tree else []
    body: List[str] = []
    tables: List[Tuple[str, str]] = []

    for node in tree.body if tree else []:
        if not isinstance(node, ast.ClassDef):
            continue
        table_name = None
        columns: List[List[str]] = []
        for item in node.body:
            if not isinstance(item, ast.Assign) or len(item.targets) != 1:
                continue
            target = item.targets[0]
            if not isinstance(target, ast.Name):
                continue
            if target.id == "__tablename__":
                table_name = const_str(item.value)
                continue
            call = item.value
            if not (isinstance(call, ast.Call) and dotted(call.func) == "Column"):
                continue
            col_type, flags = "", []
            for arg in call.args:
                if isinstance(arg, ast.Call) and dotted(arg.func) == "ForeignKey":
                    flags.append(f"FK → `{const_str(arg.args[0]) if arg.args else '?'}`")
                elif not col_type:
                    col_type = ast.unparse(arg)
            default = ""
            for kw in call.keywords:
                if kw.arg == "primary_key" and getattr(kw.value, "value", False) is True:
                    flags.insert(0, "PK")
                elif kw.arg == "unique" and getattr(kw.value, "value", False) is True:
                    flags.append("unique")
                elif kw.arg == "nullable" and getattr(kw.value, "value", True) is False:
                    flags.append("not null")
                elif kw.arg == "default":
                    default = "(computed)" if isinstance(kw.value, ast.Lambda) \
                        else ast.unparse(kw.value)
            columns.append([
                code(target.id), code(col_type), cell(", ".join(flags)),
                code(default), cell(column_comment(lines, item)),
            ])
        if not table_name:
            continue
        tables.append((table_name, node.name))
        section = [f"## `{table_name}`", "", f"Model `{node.name}`."]
        doc = first_line(ast.get_docstring(node))
        if doc:
            section[-1] += f" {doc}."
        section += ["", table(["Column", "Type", "Constraints", "Default", "Notes"], columns)]
        body.append("\n".join(section))

    # Migrations, and whether every dialect has every version.
    versions = migration_versions()
    migration_rows = []
    gaps = 0
    for version in sorted(versions):
        present = versions[version]
        name = next(iter(present[d] for d in SQL_DIALECTS if d in present))
        marks = ["✓" if d in present else "✗" for d in SQL_DIALECTS]
        gaps += marks.count("✗")
        migration_rows.append([f"V{version:03d}", cell(name.replace("_", " "))] + marks)

    latest = f"V{max(versions):03d}" if versions else "none"
    intro = [
        f"**{len(tables)}** tables defined in `{MODELS}`; migrations are at **{latest}**. "
        "Migrations apply automatically on startup and are the source of truth for the "
        "schema: the models describe it, the migrations create it.",
        "",
        "## Migrations",
        "",
        "A ✗ means that dialect has no file for that version."
        + (f" **{gaps} gap(s) found.**" if gaps else " All dialects are in step."),
        "",
        table(["Version", "Name"] + list(SQL_DIALECTS), migration_rows),
        "",
    ]
    return page(
        "Database reference",
        "Every table and column from the ORM models, plus the migration history per dialect.",
        40, "\n".join(intro) + "\n" + "\n\n".join(body),
    )


def build_reference() -> Dict[str, str]:
    sources = python_sources(tracked_files())
    return {
        "configuration.md": render_configuration(sources),
        "api.md": render_api(sources),
        "tools.md": render_tools(),
        "database.md": render_database(),
    }


# --------------------------------------------------------------------------- #
# Guides: frontmatter, lint, drift                                             #
# --------------------------------------------------------------------------- #

def read_frontmatter(path: Path) -> Tuple[Dict[str, Any], str]:
    """Parse the small YAML subset guides use: scalars, ``[a, b]`` and ``- item`` lists."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---", 4)
    if end == -1:
        return {}, text
    meta: Dict[str, Any] = {}
    current: Optional[str] = None
    for raw in text[4:end].splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        item = re.match(r"^\s+-\s+(.*)$", raw)
        if item and current:
            meta.setdefault(current, [])
            if isinstance(meta[current], list):
                meta[current].append(item.group(1).strip().strip("\"'"))
            continue
        pair = re.match(r"^([A-Za-z_][\w-]*):\s*(.*)$", raw)
        if not pair:
            continue
        current, value = pair.group(1), pair.group(2).strip()
        if value == "":
            meta[current] = []
        elif value.startswith("[") and value.endswith("]"):
            meta[current] = [v.strip().strip("\"'") for v in value[1:-1].split(",") if v.strip()]
        else:
            meta[current] = value.strip("\"'")
    return meta, text[end + 4:]


def guides() -> List[Path]:
    found: List[Path] = []
    for folder in GUIDE_DIRS.values():
        if folder.is_dir():
            found.extend(sorted(folder.rglob("*.md")))
    return found


def symbols(source: str, pattern: str) -> Dict[str, str]:
    """Functions and classes whose name matches ``pattern``, keyed to a body fingerprint.

    The fingerprint is ``ast.dump``: it ignores comments and formatting, so only a
    change in behaviour counts as a change.
    """
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return {}
    out: Dict[str, str] = {}
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)) \
                and fnmatch.fnmatchcase(node.name, pattern):
            out[node.name] = out.get(node.name, "") + ast.dump(node)
    return out


def split_cover(entry: str) -> Tuple[str, Optional[str]]:
    path, sep, symbol = entry.partition("::")
    return path, (symbol if sep else None)


def lint_guides(files: Sequence[str]) -> List[str]:
    problems: List[str] = []
    file_set = set(files)
    for guide in guides():
        name = rel(guide)
        meta, body = read_frontmatter(guide)
        if not meta:
            problems.append(f"{name}: missing frontmatter")
            continue
        for key in ("title", "summary", "audience", "covers"):
            if key not in meta:
                problems.append(f"{name}: frontmatter is missing `{key}`")
        expected = guide.relative_to(DOCS_DIR).parts[0]
        if meta.get("audience") not in (None, expected):
            problems.append(
                f"{name}: audience is `{meta.get('audience')}` but the file is under docs/{expected}/"
            )
        covers = meta.get("covers") or []
        if not isinstance(covers, list):
            problems.append(f"{name}: `covers` must be a list")
            covers = []
        for entry in covers:
            path, symbol = split_cover(entry)
            regex = glob_to_regex(path)
            matched = [f for f in files if regex.match(f)]
            if not matched:
                problems.append(f"{name}: `covers` entry `{entry}` matches no file (renamed or removed?)")
            elif symbol and not any(
                symbols((ROOT / f).read_text(encoding="utf-8"), symbol) for f in matched
            ):
                problems.append(f"{name}: `covers` entry `{entry}` matches no function or class")
        for link in re.findall(r"\]\(([^)\s]+)\)", body):
            if re.match(r"^(https?:|mailto:|#|/)", link):
                continue
            target = (guide.parent / link.split("#", 1)[0]).resolve()
            try:
                target_rel = target.relative_to(ROOT).as_posix()
            except ValueError:
                target_rel = ""
            if target_rel not in file_set and not target.exists():
                problems.append(f"{name}: broken link `{link}`")
    return problems


def git(*args: str) -> Optional[str]:
    try:
        return subprocess.run(
            ["git", *args], cwd=ROOT, capture_output=True, text=True, check=True,
        ).stdout
    except (OSError, subprocess.CalledProcessError):
        return None


def find_drift(base: str) -> Tuple[List[Tuple[str, List[str]]], Optional[str]]:
    """Guides whose covered code changed since ``base`` while the guide did not."""
    merge_base = (git("merge-base", base, "HEAD") or "").strip()
    if not merge_base:
        return [], f"cannot resolve base `{base}` (shallow clone? fetch it first)"
    diff = git("diff", "--name-only", merge_base)
    if diff is None:
        return [], "git diff failed"
    changed = {line for line in diff.splitlines() if line}
    untracked = git("ls-files", "--others", "--exclude-standard") or ""
    changed |= {line for line in untracked.splitlines() if line}

    stale: List[Tuple[str, List[str]]] = []
    for guide in guides():
        name = rel(guide)
        if name in changed:
            continue
        meta, _ = read_frontmatter(guide)
        reasons: List[str] = []
        for entry in meta.get("covers") or []:
            path, symbol = split_cover(entry)
            regex = glob_to_regex(path)
            for changed_file in sorted(f for f in changed if regex.match(f)):
                if symbol is None:
                    reasons.append(changed_file)
                    continue
                before = git("show", f"{merge_base}:{changed_file}") or ""
                current = ROOT / changed_file
                after = current.read_text(encoding="utf-8") if current.is_file() else ""
                if symbols(before, symbol) != symbols(after, symbol):
                    reasons.append(f"{changed_file}::{symbol}")
        if reasons:
            stale.append((name, sorted(set(reasons))))
    return stale, None


def coverage_report(files: Sequence[str]) -> Tuple[List[str], List[str]]:
    scope = [
        f for f in files
        if any(glob_to_regex(g).match(f) for g in COVERAGE_GLOBS)
        and f.endswith((".py", ".html", ".js"))
        and not f.endswith("__init__.py")
        and not f.startswith(SKIP_PREFIXES)
    ]
    patterns = []
    for guide in guides():
        meta, _ = read_frontmatter(guide)
        for entry in meta.get("covers") or []:
            patterns.append(glob_to_regex(split_cover(entry)[0]))
    covered = [f for f in scope if any(p.match(f) for p in patterns)]
    uncovered = [f for f in scope if f not in set(covered)]
    return covered, uncovered


# --------------------------------------------------------------------------- #
# Commands                                                                     #
# --------------------------------------------------------------------------- #

def cmd_generate(check: bool) -> int:
    reference = build_reference()
    stale: List[str] = []
    for name, content in reference.items():
        target = REFERENCE_DIR / name
        current = target.read_text(encoding="utf-8") if target.is_file() else None
        if current == content:
            continue
        stale.append(rel(target) if target.exists() else f"docs/reference/{name}")
        if not check:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")

    if not check:
        print(f"docs/reference: {len(reference)} pages, {len(stale)} updated")
        return 0

    failed = False
    reads = collect_env_reads(python_sources(tracked_files()))
    conflicts, undocumented = configuration_gaps(reads, parse_env_example())
    if conflicts:
        failed = True
        print("Conflicting environment variable defaults (define the default once in shared/utils/settings.py):")
        for name in conflicts:
            defaults = ", ".join(sorted(reads[name]["defaults"]))
            files = ", ".join(sorted(reads[name]["files"]))
            print(f"  - {name}: defaults {defaults}; read in {files}")
    missing = [name for name in undocumented if name not in ENV_EXAMPLE_ALLOWLIST]
    if missing:
        failed = True
        print("Environment variables missing from .env.example (add a commented line with a description):")
        for name in missing:
            print(f"  - {name}")
    if stale:
        failed = True
        print("Generated reference is out of date. Run `python scripts/gen_docs.py` and commit:")
        for name in stale:
            print(f"  - {name}")
    problems = lint_guides(tracked_files())
    if problems:
        failed = True
        print("Guide problems:")
        for problem in problems:
            print(f"  - {problem}")
    gaps = migration_gaps()
    if gaps:
        failed = True
        print("Migrations missing from a dialect (add the file to shared/sql/migrations/<dialect>/):")
        for gap in gaps:
            print(f"  - {gap}")
    if not failed:
        print(f"docs OK: {len(reference)} reference pages current, {len(guides())} guides well-formed")
        unverified = [rel(g) for g in guides() if read_frontmatter(g)[0].get("status") == "migrated"]
        if unverified:
            print(f"{len(unverified)} guide(s) still marked `status: migrated` (not re-checked against the code)")
    return 1 if failed else 0


def cmd_drift(base: str, strict: bool) -> int:
    stale, error = find_drift(base)
    if error:
        print(f"drift check skipped: {error}")
        return 1 if strict else 0
    if not stale:
        print(f"No guide drift against {base}.")
        return 0
    in_actions = os.getenv("GITHUB_ACTIONS") == "true"
    print(f"{len(stale)} guide(s) describe code that changed but were not updated:")
    for name, reasons in stale:
        print(f"  - {name}")
        for reason in reasons:
            print(f"      {reason}")
        if in_actions:
            level = "error" if strict else "warning"
            print(f"::{level} file={name}::Covered code changed without this guide: "
                  f"{', '.join(reasons)}")
    print("Update the guide, or confirm it is still accurate and say so in the PR.")
    return 1 if strict else 0


def cmd_coverage() -> int:
    covered, uncovered = coverage_report(tracked_files())
    total = len(covered) + len(uncovered)
    percent = (100 * len(covered) // total) if total else 0
    print(f"Guide coverage: {len(covered)}/{total} source files ({percent}%)")
    by_dir: Dict[str, List[str]] = {}
    for path in uncovered:
        by_dir.setdefault(os.path.dirname(path) or ".", []).append(os.path.basename(path))
    for folder in sorted(by_dir):
        print(f"\n{folder}/ ({len(by_dir[folder])} uncovered)")
        for name in sorted(by_dir[folder]):
            print(f"  {name}")
    return 0


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="fail if docs/reference is stale or a guide is malformed")
    sub = parser.add_subparsers(dest="command")
    drift = sub.add_parser("drift", help="report guides whose covered code changed")
    drift.add_argument("--base", default="origin/main", help="git ref to compare against")
    drift.add_argument("--strict", action="store_true", help="exit 1 when a guide is stale")
    sub.add_parser("coverage", help="list source files no guide covers")
    args = parser.parse_args(argv)

    if args.command == "drift":
        return cmd_drift(args.base, args.strict)
    if args.command == "coverage":
        return cmd_coverage()
    return cmd_generate(args.check)


if __name__ == "__main__":
    sys.exit(main())
